# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

type = "backend"
roles = ["main"]

[commands]
dev = "npm run dev"
build = "npm run build"
start = "npm run start"

[hmr]
pubsub_port = 8023
pubsub_host = "localhost"